//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsercizioMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPiatti
    {
        public int id { get; set; }
        public Nullable<int> menu { get; set; }
        public Nullable<int> piatto { get; set; }
    
        public virtual Menu Menu1 { get; set; }
        public virtual Piatti Piatti { get; set; }
    }
}
