//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsercizioMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piatti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Piatti()
        {
            this.MenuPiatti = new HashSet<MenuPiatti>();
        }
    
        public int id { get; set; }
        public Nullable<int> portata { get; set; }
        public string descrizione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuPiatti> MenuPiatti { get; set; }
        public virtual Portate Portate { get; set; }
    }
}
